# Generated by Django 3.2 on 2022-06-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equitybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equity',
            options={'ordering': ['-id']},
        ),
    ]
